using NeoFPS;
using UnityEngine;

namespace RogueWave
{
    public class ProceduralTile : BaseTile
    {
        [SerializeField, Tooltip("A configuration for the level generator that will create the content of this tile.")]
        LevelDefinition tileLevelDefinition;
        
        internal override void GenerateTileContent(int x, int y, BaseTile[,] tiles)
        {
            this.levelGenerator = gameObject.AddComponent<LevelGenerator>();
            this.levelGenerator.levelDefinition = tileLevelDefinition;
            this.levelGenerator.Generate(tileLevelDefinition, Vector3.zero, transform);
            Destroy(this.levelGenerator);
        }

        protected override void GenerateGround(int x, int y, BaseTile[,] tiles)
        {
            // will be generated by the contained tiles
        }

    }


}