using NeoFPS;
using UnityEngine;

namespace RogueWave
{
    /// <summary>
    /// A WFCTile is a tile that is generated using the Wave Function Collapse algorithm.
    /// It will have its own WFCDefinition that will be used to generate the content of the tile, but additional constraints may be added by a parent WfcDefinition.
    /// That is WfcTiles can be used to create a level that is made up of smaller tiles that are also generated using WFC. In this constraints on generations, such
    /// as availble tiles, can be inherited from the parent WfcDefinition.
    /// </summary>
    public class WfcTile : BaseTile
    {
        [SerializeField, Tooltip("A configuration for the Wave Function Collapse algorithm that will create the content of this tile. Note that if this tile is being generated as a child of another WFC generated object it will inherit some constraints from that parent.")]
        WfcDefinition wfcDefinition;

        internal override void GenerateTileContent(int x, int y, BaseTile[,] tiles, LevelGenerator parent)
        {
            levelGenerator = gameObject.AddComponent<LevelGenerator>();
            levelGenerator.parentGenerator = parent;
            levelGenerator.levelDefinition = wfcDefinition;
            levelGenerator.Generate(wfcDefinition, Vector3.zero, transform, -1);
            Destroy(levelGenerator);
        }

        protected override void GenerateGround(int x, int y, BaseTile[,] tiles, LevelGenerator parent)
        {
            // will be generated by the contained tiles
        }

    }


}